name: Goals M3U Bot

on:
  # Manuel tetikleme
  workflow_dispatch:
  # Otomatik tetikleme: her 5 dakikada bir
  schedule:
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodları çek
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Gerekli paketleri yükle
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: goals.py çalıştır
        run: python goals.py

      - name: goals.m3u dosyasını kaydet
        uses: actions/upload-artifact@v3
        with:
          name: goals-m3u
          path: goals.m3u
