name: Pornoanne Scraper

on:
  workflow_dispatch:  # manuel tetikleme

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Repo'yu checkout et
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Gereksinimleri kur
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Scraper çalıştır
        run: |
          python olimpus.py

      - name: Commit & push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add pornoanne.m3u
          git commit -m "M3U güncellendi [manual run]"
          git push
