name: Pornoanne Scraper

on:
  workflow_dispatch:  # Manuel tetikleme

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Gereksinimleri yükle
        run: |
          python -m pip install --upgrade pip
          pip install cloudscraper beautifulsoup4

      - name: Scripti çalıştır
        run: python olimpus.py
