name: Update YouTube Live M3U8

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Generate M3U8
        run: python restream.py

      - name: Commit and push
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions"
          git add 1siriustv.m3u8
          git commit -m "Update live stream playlist" || echo "No changes"
          git push
