name: Selcuk M3U Güncelleme

on:
  schedule:
    - cron: "*/15 * * * *"   # Her 15 dakikada bir çalışır
  workflow_dispatch:          # Elle çalıştırabilmen için

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Tüm geçmişi indir, yoksa push hatası olur

      - name: Python Kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Gerekli Kütüphaneleri Kur
        run: pip install requests

      - name: Botu Çalıştır
        run: python bot.py   # Burada bot.py senin m3u yazan scriptin

      - name: Değişiklikleri Commit Et ve Pushla
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add selcuk.m3u
            git commit -m "🔄 Selcuk güncellendi ($(date '+%Y-%m-%d %H:%M:%S'))"
            git pull --rebase
            git push
          else
            echo "📂 Değişiklik yok, commit atılmadı."
          fi
