name: Update Selcuk M3U

on:
  workflow_dispatch: # manuel tetikleme
  schedule: # her 5 dakikada bir otomatik
    - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Requests
        run: pip install requests

      - name: Run Selcuk Bot
        run: python selcuk.py

      - name: Commit selcuk.m3u
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add selcuk.m3u
          git commit -m "Update selcuk.m3u" || echo "No changes to commit"
          git push
