name: Selcuk kontrol

on:
  workflow_dispatch:   # Elle çalıştırmak için
  schedule:
    - cron: '*/15 * * * *'   # 15 dakikada bir çalıştır

jobs:
  BirlesikGuncelleme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      - name: Python 3.11 Yükle
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Gereksinimleri Kur
        run: |
          python -m pip install --upgrade pip
          pip install Kekik httpx parsel requests

      - name: selcuk.py Çalıştır
        run: python selcuk.py

      - name: Değişiklikleri Commit Et
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add selcuk.m3u
            git commit -m "🔄 Selcuk güncellendi ($(date '+%Y-%m-%d %H:%M:%S'))"
            git push
          else
            echo "Değişiklik yok, commit atılmadı."
          fi
