name: Scrape ShowTV

on:
  schedule:
    - cron: "0 */12 * * *"  # 12 saatte bir çalışır
  workflow_dispatch: # Manuel çalıştırma

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install deps
        run: pip install requests beautifulsoup4

      - name: Run scraper
        run: python show.py   # <- burada show.py çalışıyor

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add showtv.m3u
          git commit -m "Update playlist" || echo "No changes to commit"
          git push
