name: Run tgbot every 5 minutes

on:
  schedule:
    - cron: "*/5 * * * *"   # her 5 dakikada bir çalıştırır
  workflow_dispatch:        # elle çalıştırmak için

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-telegram-bot

      - name: Run bot script
        run: python tgbot.py

      - name: Commit tgbot.txt
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add tgbot.txt
          git commit -m "Auto update tgbot.txt" || echo "No changes to commit"
          git push
