name: Build M3U

on:
  workflow_dispatch:   # Manuel çalıştırma
  schedule:
    - cron: "0 */6 * * *"   # 6 saatte bir otomatik çalışsın (UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run tv.py
        run: |
          python tv.py

      - name: Commit and push generated M3U
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add TheTVApp.m3u
          git commit -m "Auto update TheTVApp.m3u"
          git push
